name: Refresh Token

on:
  push:
    branches: [ dev ]
  pull_request:
    paths:
      - "REMOTES.txt"
  workflow_dispatch:
  schedule:
   - cron: '0 */48 * * *'
  watch:
    types: [started]

permissions: write-all

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_REPOSITORY: $GITHUB_REPOSITORY
  RCLONE_CONFIG_FILE: ${{ secrets.RCLONE_CONFIG_FILE }}
  SECRET_REMOTES: ${{ secrets.REMOTES }}
  VAR_REMOTES: ${{ vars.REMOTES }}
  WORKSPACE: ${{ github.WORKSPACE }}
  TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

jobs:
  Refresh_Token:
    runs-on: ubuntu-latest
#    timeout-minutes: 5

    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Cache Rclone installation
      uses: actions/cache@main
      id: cache-rclone
      if: ${{ always() }}
      with:
          path: |
            **/rclone
          key: cache-rclone
          
    - name: Install Rclone
      if: steps.cache-rclone.outputs.cache-hit != 'true'
      run: Scripts/Install_Rclone.sh

    - name: Download rlcone.conf
      if: ${{ env.RCLONE_CONFIG_FILE }}
      run: |
        rm -f rclone.conf
        wget -O rclone.conf ${{ env.RCLONE_CONFIG_FILE }} > /dev/null 2>&1

    - name: Recreate REMOTES.txt if it is in variable
      if: ${{ env.VAR_REMOTES }}
      run: |
        rm -f REMOTES.txt
        if [[ "${{ env.VAR_REMOTES }}" == "https://"* ]]; then
          wget -O REMOTES.txt ${{ env.VAR_REMOTES }}
        else
          echo "${{ env.VAR_REMOTES }}" > REMOTES.txt
        fi

    - name: Recreate REMOTES.txt if it is in secret
      if: ${{ env.SECRET_REMOTES }}
      run: |
        rm -f REMOTES.txt
        if [[ "${{ env.SECRET_REMOTES }}" == "https://"* ]]; then
          wget -O REMOTES.txt ${{ env.SECRET_REMOTES }} > /dev/null 2>&1
        else
          echo "${{ env.SECRET_REMOTES }}" > REMOTES.txt  > /dev/null 2>&1
        fi

    - name: Refresh Token
#      if: ${{ env.TELEGRAM_TOKEN != '' && env.TELEGRAM_TO != '' }} # Remove this hashtag if you want to exclude this step when TELEGRAM_TO and TELEGRAM_TOKEN are set. Default is always run this step.
      run: Scripts/Refresh_Token.sh

    - name: Refresh Token and redirect output to refresh_token_log.txt
      if: ${{ env.TELEGRAM_TOKEN && env.TELEGRAM_TO }}
      run: |
        # DELETE OLD REFRESH_TOKEN_LOG.TXT IF NEED
        rm -rf refresh_token_log.txt

        # REDIRECT THE LOG INTO REFRESH_TOKEN_LOG.TXT
        exec > refresh_token_log.txt 2>&1

        Scripts/Refresh_Token.sh

    - name: Send log to Telegram
      if: ${{ env.TELEGRAM_TOKEN && env.TELEGRAM_TO }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message_file: refresh_token_log.txt