name: Send log to Github

on:
  workflow_call:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

jobs:
  Send_log_to_Telegram:
    runs-on: ubuntu-latest
    steps:

    - name: Download artifact
      uses: actions/download-artifact@main
      with:
        name: refresh_token_log
        path: refresh_token_log.txt

    - name : Send log
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message_file: refresh_token_log.txt
        disable_notification: true